CREATE PROCEDURE SEC.REBUILD_PermiratedUserLink
AS BEGIN

BEGIN TRY
DROP INDEX [IX_RLS_PERMITATION] ON [Sec].[PermiratedUserLink] WITH ( ONLINE = OFF )
END TRY
BEGIN CATCH 
PRINT 'IX Did Not Exist'
END CATCH

TRUNCATE TABLE [Sec].[PermiratedUserLink]

INSERT INTO [Sec].[PermiratedUserLink]
SELECT DISTINCT * FROM [Sec].[vPermiratedUserLink] ORDER BY 1,2




CREATE UNIQUE CLUSTERED INDEX [IX_RLS_PERMITATION] ON [Sec].[PermiratedUserLink]
(
	[RLSUserID] ASC,
	[PermitationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]



END